# Generated by Django 5.0.3 on 2024-03-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('case_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cite_text', models.TextField()),
            ],
        ),
    ]
